name: Checks

on:
  push:
    branches:
      - '*'  # Run for every branch

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          # TODO Add rule to get all the dependencies
          # make deps

      - name: Check commit messages
        run: |
          # Define the regular expression
          REGEX='(^(feat|fix|docs|style|refactor|perf|test|chore|build|ci|revert)[!]{0,1}: .+)|(^Initial commit$)'
          
          # Get the commits SHAs in the PR by compairing the base
          COMMITS=$(git log --pretty=format:"%h" ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }})

          # Iterate for each commit and validate the message
          for COMMIT in $COMMITS; do
            MESSAGE=$(git log -1 --pretty=format:"%s" $COMMIT)
            echo "Checking commit: $COMMIT - $MESSAGE"
            if ! grep -qE "$REGEX" <<< "$MESSAGE"; then
              echo "Error: El commit '$MESSAGE' no cumple con el formato de Conventional Commits."
              exit 1
            fi
          done
          echo "Todos los commits cumplen con el formato de Conventional Commits."

      - name: Check formatting
        run: |
          # TODO Add rule to format your source code
          # make format
          git diff --exit-code || (echo "Formatting issues detected!" && exit 1)

      - name: Run linter
        run: |
          # TODO Add rule to run any linter
          # make lint

