name: Checks

on:
  push:
    branches:
      - '*'  # Run for every branch

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          # TODO Add rule to get all the dependencies
          # make deps

      - name: Check commit messages
        run: |
          set -e
          success=1
          for hash in $(git rev-list origin..HEAD); do
            git log -1 --pretty=%s $hash \
              | grep -qE '(^(feat|fix|docs|style|refactor|perf|test|chore|build|ci|revert)[!]{0,1}: .+)|(^Initial commit$)' \
              || { git log -1 --pretty="%t %s" "$hash"; success=0; }
          done
          if [ "$success" -eq 0 ]; then
            echo "error: some commit message does not match conventional commits"
            echo "error: please check the above commits"
            exit 1
          fi
          echo "title match conventional commits: success"

      - name: Check formatting
        run: |
          # TODO Add rule to format your source code
          # make format
          git diff --exit-code || (echo "Formatting issues detected!" && exit 1)

      - name: Run linter
        run: |
          # TODO Add rule to run any linter
          # make lint

